application: quakeinfoprod
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
 - appstats: on

libraries:
- name: jinja2
  version: "2.6"
- name: PIL
  version: "1.1.7"
- name: webapp2
  version: "2.5.1"

handlers:
- url: /(.*\.html)
  mime_type: text/html
  static_files: static/\1
  upload: static/(.*\.html)
  expiration: "1h"
  
- url: /scripts
  static_dir: scripts

- url: /images
  static_dir: images
    
- url: /html
  static_dir: html
  
- url: /.*
  script: main.app
